# Pandas

In [1]:
import pandas as pd

In [2]:
# Criar um DataFrame Vazio
df = pd.DataFrame()

In [11]:
# Criando um DataFrame a partir de um Dicionário
Lay_Goleada_Punter = {'Mandante' : ['Norrkoping', 'Trelleborgs','IA Akranes'],
                      'Visitante' : ['IFK Goteborg', 'Skovde Aik', 'Fram'],
                      'Valor da Odd' : [9.40, 13.50, 16],
                      'Lucro Sobre a Stake (em %)' : [11.9, 8.0, 6.7]}

In [9]:
df_LGP = pd.DataFrame(Lay_Goleada_Punter)

In [10]:
df_LGP

      Mandante     Visitante  Valor da Odd  Lucro Sobre a Stake (em %)
0   Norrkoping  IFK Goteborg           9.4                        11.9
1  Trelleborgs    Skovde Aik          13.5                         8.0
2   IA Akranes          Fram          16.0                         6.7

In [17]:
df_LGP = pd.DataFrame(df_LGP, columns = ['Mandante','Visitante','Lucro Sobre a Stake (em %)','Campeonato'])

In [19]:
df_LGP['Campeonato'] = 'Suécia'

In [20]:
df_LGP

      Mandante     Visitante  Lucro Sobre a Stake (em %) Campeonato
0   Norrkoping  IFK Goteborg                        11.9     Suécia
1  Trelleborgs    Skovde Aik                         8.0     Suécia
2   IA Akranes          Fram                         6.7     Suécia

In [24]:
lista = [9.40, 13.50, 16]
df_LGP['Odd'] = pd.DataFrame(lista)
df_LGP

      Mandante     Visitante  Lucro Sobre a Stake (em %) Campeonato   Odd
0   Norrkoping  IFK Goteborg                        11.9     Suécia   9.4
1  Trelleborgs    Skovde Aik                         8.0     Suécia  13.5
2   IA Akranes          Fram                         6.7     Suécia  16.0

In [25]:
df_LGP['Probabilidade'] = round(100/df_LGP.Odd, 2)
df_LGP

,Mandante,Visitante,Lucro Sobre a Stake (em %),Campeonato,Odd,Probabilidade
0,Norrkoping,IFK Goteborg,11.9,Suécia,9.4,10.64
1,Trelleborgs,Skovde Aik,8.0,Suécia,13.5,7.41
2,IA Akranes,Fram,6.7,Suécia,16.0,6.25

In [26]:
df_LGP.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 6 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Mandante                    3 non-null      object
 1   Visitante                   3 non-null      object
 2   Lucro Sobre a Stake (em %)  3 non-null      float64
 3   Campeonato                  3 non-null      object
 4   Odd                         3 non-null      float64
 5   Probabilidade               3 non-null      float64
dtypes: float64(3), object(3)
memory usage: 272.0+ bytes

In [27]:
df_LGP.describe()

       Lucro Sobre a Stake (em %)        Odd  Probabilidade
count                    3.000000   3.000000       3.000000
mean                     8.866667  12.966667       8.100000
std                      2.706166   3.332166       2.274885
min                      6.700000   9.400000       6.250000
25%                      7.350000  11.450000       6.830000
50%                      8.000000  13.500000       7.410000
75%                      9.950000  14.750000       9.025000
max                     11.900000  16.000000      10.640000

In [28]:
# Criar um DataFrame a partir de um csv e do Excel
brasil = pd.read_csv('https://www.football-data.co.uk/new/BRA.csv')

In [31]:
brasil.describe()

,Season,HG,AG,PH,PD,PA,MaxH,MaxD,MaxA,AvgH,AvgD,AvgA
count,3980.000000,3979.000000,3979.000000,3979.000000,3979.000000,3979.000000,3980.000000,3980.000000,3980.000000,3980.000000,3980.000000,3980.000000
mean,2016.748744,1.412666,0.944710,2.303916,3.654486,4.708716,2.384550,3.757791,4.967093,2.226359,3.483809,4.337588
std,3.030744,1.157354,0.971157,0.958146,0.656244,2.511148,1.073876,0.682924,2.804649,0.893490,0.567769,2.147462
min,2012.000000,0.000000,0.000000,1.080000,2.540000,1.150000,1.090000,2.630000,0.000000,1.070000,2.510000,1.150000
25%,2014.000000,1.000000,0.000000,1.690000,3.260000,2.990000,1.740000,3.347500,3.060000,1.650000,3.150000,2.857500
50%,2017.000000,1.000000,1.000000,2.080000,3.460000,4.010000,2.150000,3.540000,4.150000,2.030000,3.300000,3.730000
75%,2019.000000,2.000000,1.000000,2.610000,3.860000,5.770000,2.700000,3.960000,6.092500,2.520000,3.660000,5.320000
max,2022.000000,6.000000,6.000000,17.680000,12.250000,29.580000,29.000000,12.500000,36.000000,20.230000,10.820000,26.580000

In [33]:
brasil.head(10)

,Country,League,Season,Date,Time,Home,Away,HG,AG,Res,PH,PD,PA,MaxH,MaxD,MaxA,AvgH,AvgD,AvgA
0,Brazil,Serie A,2012,19/05/2012,22:30,Palmeiras,Portuguesa,1.0,1.0,D,1.75,3.86,5.25,1.76,3.87,5.31,1.69,3.50,4.90
1,Brazil,Serie A,2012,19/05/2012,22:30,Sport Recife,Flamengo RJ,1.0,1.0,D,2.83,3.39,2.68,2.83,3.42,2.70,2.59,3.23,2.58
2,Brazil,Serie A,2012,20/05/2012,01:00,Figueirense,Nautico,2.0,1.0,H,1.60,4.04,6.72,1.67,4.05,7.22,1.59,3.67,5.64
3,Brazil,Serie A,2012,20/05/2012,20:00,Botafogo RJ,Sao Paulo,4.0,2.0,H,2.49,3.35,3.15,2.49,3.39,3.15,2.35,3.26,2.84
4,Brazil,Serie A,2012,20/05/2012,20:00,Corinthians,Fluminense,0.0,1.0,A,1.96,3.53,4.41,1.96,3.53,4.41,1.89,3.33,3.89
5,Brazil,Serie A,2012,20/05/2012,20:00,Internacional,Coritiba,2.0,0.0,H,1.76,3.63,5.66,1.77,3.90,6.00,1.66,3.55,5.10
6,Brazil,Serie A,2012,20/05/2012,20:00,Ponte Preta,Atletico-MG,0.0,1.0,A,3.12,3.45,2.44,3.12,3.45,2.62,2.74,3.23,2.45
7,Brazil,Serie A,2012,20/05/2012,22:30,Bahia,Santos,0.0,0.0,D,2.33,3.44,3.32,2.45,3.52,3.32,2.30,3.22,2.97
8,Brazil,Serie A,2012,20/05/2012,22:30,Cruzeiro,Atletico GO,0.0,0.0,D,1.83,3.74,4.82,1.85,3.79,4.82,1.78,3.47,4.30
9,Brazil,Serie A,2012,20/05/2012,22:30,Vasco,Gremio,2.0,1.0,H,2.25,3.40,3.53,2.25,3.46,3.64,2.08,3.25,3.41

In [35]:
brasil.tail(10)

,Country,League,Season,Date,Time,Home,Away,HG,AG,Res,PH,PD,PA,MaxH,MaxD,MaxA,AvgH,AvgD,AvgA
3970,Brazil,Serie A,2022,20/07/2022,01:30,Ceara,Avai,1.0,0.0,H,1.38,4.76,9.52,1.50,5.25,11.00,1.34,4.83,9.44
3971,Brazil,Serie A,2022,20/07/2022,23:00,Bragantino,Fortaleza,2.0,1.0,H,1.83,3.46,5.20,1.87,3.73,5.30,1.81,3.38,4.76
3972,Brazil,Serie A,2022,20/07/2022,23:00,Goias,Fluminense,2.0,3.0,A,4.28,3.56,1.93,4.80,3.60,1.95,4.30,3.44,1.86
3973,Brazil,Serie A,2022,20/07/2022,23:30,Athletico-PR,Atletico GO,4.0,1.0,H,1.95,3.41,4.35,2.10,3.45,4.40,1.97,3.26,4.08
3974,Brazil,Serie A,2022,21/07/2022,00:30,Flamengo RJ,Juventude,4.0,0.0,H,1.34,5.49,9.31,1.37,5.49,10.00,1.34,5.11,8.63
3975,Brazil,Serie A,2022,21/07/2022,00:30,Internacional,Sao Paulo,3.0,3.0,D,1.85,3.39,5.04,1.98,3.50,5.10,1.85,3.31,4.67
3976,Brazil,Serie A,2022,21/07/2022,01:30,Corinthians,Coritiba,3.0,1.0,H,1.68,3.59,6.12,1.72,3.70,6.50,1.67,3.51,5.67
3977,Brazil,Serie A,2022,21/07/2022,01:30,Santos,Botafogo RJ,2.0,0.0,H,1.93,3.34,4.62,1.97,3.62,4.70,1.86,3.40,4.37
3978,Brazil,Serie A,2022,21/07/2022,23:00,Cuiaba,Atletico-MG,1.0,1.0,D,3.73,2.92,2.37,4.55,3.15,2.37,3.66,2.94,2.24
3979,Brazil,Serie A,2022,22/07/2022,00:00,America MG,Palmeiras,0.0,1.0,A,4.77,3.59,1.83,4.85,3.66,1.88,4.51,3.46,1.82

In [36]:
argentina = pd.read_excel('https://www.football-data.co.uk/new/ARG.xlsx')

In [38]:
argentina2 = argentina[['Home','Away', 'HG', 'AG']]

In [42]:
argentina2.columns = ['Mandante', 'Visitante','Gols Mandante', 'Gols Visitante']

In [43]:
argentina2

              Mandante          Visitante  Gols Mandante  Gols Visitante
0      Arsenal Sarandi  Union de Santa Fe              1               0
1      Velez Sarsfield     Argentinos Jrs              3               0
2          Racing Club       Atl. Rafaela              1               1
3       Colon Santa FE              Lanus              1               0
4              Quilmes       Boca Juniors              3               0
...                ...                ...            ...             ...
4051           Huracan         Godoy Cruz              0               0
4052             Lanus    Velez Sarsfield              2               2
4053   Rosario Central   Newells Old Boys              1               0
4054  Talleres Cordoba           Banfield              1               0
4055       River Plate      Gimnasia L.P.              1               0

[4056 rows x 4 columns]